ifneq (,$(wildcard .env))
include .env
export
endif

.PHONY: help up build rebuild down restart logs shell wp composer status clean info

HOST_UID := $(shell id -u)
HOST_GID := $(shell id -g)

DEV_EXEC := docker compose exec \
	--user "$(HOST_UID):$(HOST_GID)" \
	--env HOME=/tmp/wplab-dev-$(HOST_UID)

THEME_DIRS := $(patsubst %/,%,$(wildcard themes/*/))
THEMES := $(notdir $(THEME_DIRS))

PLUGINS := $(notdir $(wildcard plugins/*))
MU_PLUGINS := $(notdir $(wildcard mu-plugins/*))

SHELL_THEME_TARGETS := $(addprefix shell.theme.,$(THEMES))
SHELL_PLUGIN_TARGETS := $(addprefix shell.plugin.,$(PLUGINS))
SHELL_MU_PLUGIN_TARGETS := $(addprefix shell.mu-plugin.,$(MU_PLUGINS))

SHELL_SHORT_TARGETS := $(sort \
	$(addprefix shell.,$(THEMES)) \
	$(addprefix shell.,$(PLUGINS)) \
	$(addprefix shell.,$(MU_PLUGINS)))

$(SHELL_SHORT_TARGETS):
	@name='$(patsubst shell.%,%,$@)'; \
	matches=0; \
	workdir=''; \
	if [ -d "themes/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/themes/$$name"; \
	fi; \
	if [ -d "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins"; \
	fi; \
	if [ -d "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins"; \
	fi; \
	if [ "$$matches" -eq 0 ]; then \
		echo "Project not found: $$name"; \
		exit 1; \
	fi; \
	if [ "$$matches" -gt 1 ]; then \
		echo "Ambiguous project: $$name"; \
		echo "Use an explicit target:"; \
		[ -d "themes/$$name" ] && echo "  make shell.theme.$$name" || true; \
		[ -e "plugins/$$name" ] && echo "  make shell.plugin.$$name" || true; \
		[ -e "mu-plugins/$$name" ] && echo "  make shell.mu-plugin.$$name" || true; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress env PS1='\w\$$ ' bash --noprofile --norc -i

$(SHELL_THEME_TARGETS):
	@$(DEV_EXEC) \
		-w /workspace/themes/$(patsubst shell.theme.%,%,$@) \
		wordpress env PS1='\w\$$ ' bash --noprofile --norc -i

$(SHELL_PLUGIN_TARGETS):
	@name='$(patsubst shell.plugin.%,%,$@)'; \
	if [ -d "plugins/$$name" ]; then \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		workdir="/workspace/plugins"; \
	else \
		echo "Plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress env PS1='\w\$$ ' bash --noprofile --norc -i

$(SHELL_MU_PLUGIN_TARGETS):
	@name='$(patsubst shell.mu-plugin.%,%,$@)'; \
	if [ -d "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins"; \
	else \
		echo "MU plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress env PS1='\w\$$ ' bash --noprofile --norc -i

CHECK_THEME_TARGETS := $(addprefix check.theme.,$(THEMES))
CHECK_PLUGIN_TARGETS := $(addprefix check.plugin.,$(PLUGINS))
CHECK_MU_PLUGIN_TARGETS := $(addprefix check.mu-plugin.,$(MU_PLUGINS))

CHECK_SHORT_TARGETS := $(sort \
	$(addprefix check.,$(THEMES)) \
	$(addprefix check.,$(PLUGINS)) \
	$(addprefix check.,$(MU_PLUGINS)))

$(CHECK_THEME_TARGETS):
	@$(DEV_EXEC) \
		-w /workspace/themes/$(patsubst check.theme.%,%,$@) \
		wordpress composer check

$(CHECK_PLUGIN_TARGETS):
	@name='$(patsubst check.plugin.%,%,$@)'; \
	if [ -d "plugins/$$name" ]; then \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		workdir="/workspace/plugins"; \
	else \
		echo "Plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) -w "$$workdir" wordpress composer check

$(CHECK_MU_PLUGIN_TARGETS):
	@name='$(patsubst check.mu-plugin.%,%,$@)'; \
	if [ -d "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins"; \
	else \
		echo "MU plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) -w "$$workdir" wordpress composer check

$(CHECK_SHORT_TARGETS):
	@name='$(patsubst check.%,%,$@)'; \
	matches=0; \
	workdir=''; \
	if [ -d "themes/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/themes/$$name"; \
	fi; \
	if [ -d "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins"; \
	fi; \
	if [ -d "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins"; \
	fi; \
	if [ "$$matches" -eq 0 ]; then \
		echo "Project not found: $$name"; \
		exit 1; \
	fi; \
	if [ "$$matches" -gt 1 ]; then \
		echo "Ambiguous project: $$name"; \
		echo "Use an explicit target:"; \
		[ -d "themes/$$name" ] && echo "  make check.theme.$$name" || true; \
		[ -e "plugins/$$name" ] && echo "  make check.plugin.$$name" || true; \
		[ -e "mu-plugins/$$name" ] && echo "  make check.mu-plugin.$$name" || true; \
		exit 1; \
	fi; \
	$(DEV_EXEC) -w "$$workdir" wordpress composer check

TEST_THEME_TARGETS := $(addprefix test.theme.,$(THEMES))
TEST_PLUGIN_TARGETS := $(addprefix test.plugin.,$(PLUGINS))
TEST_MU_PLUGIN_TARGETS := $(addprefix test.mu-plugin.,$(MU_PLUGINS))

TEST_SHORT_TARGETS := $(sort \
	$(addprefix test.,$(THEMES)) \
	$(addprefix test.,$(PLUGINS)) \
	$(addprefix test.,$(MU_PLUGINS)))

$(TEST_THEME_TARGETS):
	@$(DEV_EXEC) \
		-w /workspace/themes/$(patsubst test.theme.%,%,$@) \
		wordpress composer test

$(TEST_PLUGIN_TARGETS):
	@name='$(patsubst test.plugin.%,%,$@)'; \
	if [ -d "plugins/$$name" ]; then \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		workdir="/workspace/plugins"; \
	else \
		echo "Plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) -w "$$workdir" wordpress composer test

$(TEST_MU_PLUGIN_TARGETS):
	@name='$(patsubst test.mu-plugin.%,%,$@)'; \
	if [ -d "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins"; \
	else \
		echo "MU plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) -w "$$workdir" wordpress composer test

$(TEST_SHORT_TARGETS):
	@name='$(patsubst test.%,%,$@)'; \
	matches=0; \
	workdir=''; \
	if [ -d "themes/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/themes/$$name"; \
	fi; \
	if [ -d "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins"; \
	fi; \
	if [ -d "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins"; \
	fi; \
	if [ "$$matches" -eq 0 ]; then \
		echo "Project not found: $$name"; \
		exit 1; \
	fi; \
	if [ "$$matches" -gt 1 ]; then \
		echo "Ambiguous project: $$name"; \
		echo "Use an explicit target:"; \
		[ -d "themes/$$name" ] && echo "  make test.theme.$$name" || true; \
		[ -e "plugins/$$name" ] && echo "  make test.plugin.$$name" || true; \
		[ -e "mu-plugins/$$name" ] && echo "  make test.mu-plugin.$$name" || true; \
		exit 1; \
	fi; \
	$(DEV_EXEC) -w "$$workdir" wordpress composer test

NPM_CHECK_THEME_TARGETS := $(addprefix check.npm.theme.,$(THEMES))
NPM_CHECK_PLUGIN_TARGETS := $(addprefix check.npm.plugin.,$(PLUGINS))
NPM_CHECK_MU_PLUGIN_TARGETS := $(addprefix check.npm.mu-plugin.,$(MU_PLUGINS))

NPM_CHECK_TARGETS := $(sort \
	$(addprefix check.npm.,$(THEMES)) \
	$(addprefix check.npm.,$(PLUGINS)) \
	$(addprefix check.npm.,$(MU_PLUGINS)))

NPM_TEST_TARGETS := $(sort \
	$(addprefix test.npm.,$(THEMES)) \
	$(addprefix test.npm.,$(PLUGINS)) \
	$(addprefix test.npm.,$(MU_PLUGINS)))

NPM_TEST_THEME_TARGETS := $(addprefix test.npm.theme.,$(THEMES))
NPM_TEST_PLUGIN_TARGETS := $(addprefix test.npm.plugin.,$(PLUGINS))
NPM_TEST_MU_PLUGIN_TARGETS := $(addprefix test.npm.mu-plugin.,$(MU_PLUGINS))

$(NPM_CHECK_THEME_TARGETS):
	@$(DEV_EXEC) \
		-w /workspace/themes/$(patsubst check.npm.theme.%,%,$@) \
		wordpress bash -lc '\
			. /usr/local/nvm/nvm.sh; \
			if [ -f .nvmrc ]; then \
				nvm use || exit $$?; \
			fi; \
			npm run check'

$(NPM_CHECK_PLUGIN_TARGETS):
	@name='$(patsubst check.npm.plugin.%,%,$@)'; \
	if [ -d "plugins/$$name" ]; then \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		workdir="/workspace/plugins"; \
	else \
		echo "Plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress bash -lc '\
			. /usr/local/nvm/nvm.sh; \
			if [ -f .nvmrc ]; then \
				nvm use || exit $$?; \
			fi; \
			npm run check'

$(NPM_CHECK_MU_PLUGIN_TARGETS):
	@name='$(patsubst check.npm.mu-plugin.%,%,$@)'; \
	if [ -d "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins"; \
	else \
		echo "MU plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress bash -lc '\
			. /usr/local/nvm/nvm.sh; \
			if [ -f .nvmrc ]; then \
				nvm use || exit $$?; \
			fi; \
			npm run check'

$(NPM_CHECK_TARGETS):
	@name='$(patsubst check.npm.%,%,$@)'; \
	matches=0; \
	workdir=''; \
	if [ -d "themes/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/themes/$$name"; \
	fi; \
	if [ -d "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins"; \
	fi; \
	if [ -d "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins"; \
	fi; \
	if [ "$$matches" -eq 0 ]; then \
		echo "Project not found: $$name"; \
		exit 1; \
	fi; \
	if [ "$$matches" -gt 1 ]; then \
		echo "Ambiguous project: $$name"; \
		echo "Use an explicit target:"; \
		[ -d "themes/$$name" ] && echo "  make check.npm.theme.$$name" || true; \
		[ -e "plugins/$$name" ] && echo "  make check.npm.plugin.$$name" || true; \
		[ -e "mu-plugins/$$name" ] && echo "  make check.npm.mu-plugin.$$name" || true; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress bash -lc '\
			. /usr/local/nvm/nvm.sh; \
			if [ -f .nvmrc ]; then \
				nvm use || exit $$?; \
			fi; \
			npm run check'

$(NPM_TEST_THEME_TARGETS):
	@$(DEV_EXEC) \
		-w /workspace/themes/$(patsubst test.npm.theme.%,%,$@) \
		wordpress bash -lc '\
			. /usr/local/nvm/nvm.sh; \
			if [ -f .nvmrc ]; then \
				nvm use || exit $$?; \
			fi; \
			npm run test'

$(NPM_TEST_PLUGIN_TARGETS):
	@name='$(patsubst test.npm.plugin.%,%,$@)'; \
	if [ -d "plugins/$$name" ]; then \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		workdir="/workspace/plugins"; \
	else \
		echo "Plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress bash -lc '\
			. /usr/local/nvm/nvm.sh; \
			if [ -f .nvmrc ]; then \
				nvm use || exit $$?; \
			fi; \
			npm run test'

$(NPM_TEST_MU_PLUGIN_TARGETS):
	@name='$(patsubst test.npm.mu-plugin.%,%,$@)'; \
	if [ -d "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		workdir="/workspace/mu-plugins"; \
	else \
		echo "MU plugin not found: $$name"; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress bash -lc '\
			. /usr/local/nvm/nvm.sh; \
			if [ -f .nvmrc ]; then \
				nvm use || exit $$?; \
			fi; \
			npm run test'

$(NPM_TEST_TARGETS):
	@name='$(patsubst test.npm.%,%,$@)'; \
	matches=0; \
	workdir=''; \
	if [ -d "themes/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/themes/$$name"; \
	fi; \
	if [ -d "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins/$$name"; \
	elif [ -f "plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/plugins"; \
	fi; \
	if [ -d "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins/$$name"; \
	elif [ -f "mu-plugins/$$name" ]; then \
		matches=$$((matches + 1)); \
		workdir="/workspace/mu-plugins"; \
	fi; \
	if [ "$$matches" -eq 0 ]; then \
		echo "Project not found: $$name"; \
		exit 1; \
	fi; \
	if [ "$$matches" -gt 1 ]; then \
		echo "Ambiguous project: $$name"; \
		echo "Use an explicit target:"; \
		[ -d "themes/$$name" ] && echo "  make test.npm.theme.$$name" || true; \
		[ -e "plugins/$$name" ] && echo "  make test.npm.plugin.$$name" || true; \
		[ -e "mu-plugins/$$name" ] && echo "  make test.npm.mu-plugin.$$name" || true; \
		exit 1; \
	fi; \
	$(DEV_EXEC) \
		-w "$$workdir" \
		wordpress bash -lc '\
			. /usr/local/nvm/nvm.sh; \
			if [ -f .nvmrc ]; then \
				nvm use || exit $$?; \
			fi; \
			npm run test'

node.install.%:
	@docker compose exec wordpress bash -lc '\
		. /usr/local/nvm/nvm.sh; \
		nvm install $(patsubst node.install.%,%,$@)'

node.list:
	@docker compose exec wordpress bash -lc '\
		. /usr/local/nvm/nvm.sh; \
		nvm ls'

up:
	docker compose up -d

build:
	docker compose build

rebuild:
	docker compose up -d --build

down:
	docker compose down

restart:
	docker compose restart

logs:
	docker compose logs -f

shell:
	docker compose exec wordpress bash

wp:
	docker compose exec wordpress wp --allow-root

composer:
	@$(DEV_EXEC) wordpress composer

status:
	docker compose ps

clean:
	docker compose down -v

help:
	@echo "WP Lab commands"
	@echo
	@echo "Environment"
	@echo "  make up                       Start the site"
	@echo "  make down                     Stop the site"
	@echo "  make build                    Build containers"
	@echo "  make rebuild                  Rebuild and start containers"
	@echo "  make restart                  Restart containers"
	@echo "  make logs                     Follow container logs"
	@echo "  make status                   Show container status"
	@echo "  make clean                    Remove containers and volumes"
	@echo
	@echo "Development shells"
	@echo "  make shell                    Open the WordPress container shell"
	@echo "  make shell.NAME               Open a project shell"
	@echo "  make shell.theme.NAME         Open a theme shell"
	@echo "  make shell.plugin.NAME        Open a plugin shell"
	@echo "  make shell.mu-plugin.NAME     Open an MU-plugin shell"
	@echo
	@echo "Composer"
	@echo "  make composer                 Run Composer"
	@echo "  make check.NAME               Run Composer check"
	@echo "  make check.theme.NAME         Run Composer check for a theme"
	@echo "  make check.plugin.NAME        Run Composer check for a plugin"
	@echo "  make check.mu-plugin.NAME     Run Composer check for an MU plugin"
	@echo "  make test.NAME                Run Composer test"
	@echo "  make test.theme.NAME          Run Composer test for a theme"
	@echo "  make test.plugin.NAME         Run Composer test for a plugin"
	@echo "  make test.mu-plugin.NAME      Run Composer test for an MU plugin"
	@echo
	@echo "npm"
	@echo "  make check.npm.NAME           Run npm check"
	@echo "  make check.npm.theme.NAME     Run npm check for a theme"
	@echo "  make check.npm.plugin.NAME    Run npm check for a plugin"
	@echo "  make check.npm.mu-plugin.NAME Run npm check for an MU plugin"
	@echo "  make test.npm.NAME            Run npm test"
	@echo "  make test.npm.theme.NAME      Run npm test for a theme"
	@echo "  make test.npm.plugin.NAME     Run npm test for a plugin"
	@echo "  make test.npm.mu-plugin.NAME  Run npm test for an MU plugin"
	@echo
	@echo "Node / NVM"
	@echo "  make node.list                List installed Node versions"
	@echo "  make node.install.VERSION     Install a Node version"
	@echo
	@echo "WordPress"
	@echo "  make wp                       Run WP-CLI"
	@echo
	@echo "NAME targets are discovered from themes/, plugins/, and mu-plugins/."

help.%:
	@case "$*" in \
    		up) \
			echo "Usage:"; \
			echo "  make up"; \
			echo; \
			echo "Starts the site containers in detached mode."; \
			;; \
		down) \
			echo "Usage:"; \
			echo "  make down"; \
			echo; \
			echo "Stops and removes the site containers."; \
			;; \
		build) \
			echo "Usage:"; \
			echo "  make build"; \
			echo; \
			echo "Builds the site container images."; \
			;; \
		rebuild) \
			echo "Usage:"; \
			echo "  make rebuild"; \
			echo; \
			echo "Rebuilds the images and starts the site."; \
			;; \
		restart) \
			echo "Usage:"; \
			echo "  make restart"; \
			echo; \
			echo "Restarts the running site containers."; \
			;; \
		logs) \
			echo "Usage:"; \
			echo "  make logs"; \
			echo; \
			echo "Follows Docker Compose logs."; \
			;; \
		status) \
			echo "Usage:"; \
			echo "  make status"; \
			echo; \
			echo "Shows the current Docker Compose container status."; \
			;; \
		clean) \
			echo "Usage:"; \
			echo "  make clean"; \
			echo; \
			echo "Stops the site and removes its Docker volumes."; \
			;; \
		shell) \
			echo "Usage:"; \
			echo "  make shell.NAME"; \
			echo "  make shell.theme.NAME"; \
			echo "  make shell.plugin.NAME"; \
			echo "  make shell.mu-plugin.NAME"; \
			echo; \
			echo "Opens an interactive shell in the selected project."; \
			;; \
		check) \
			echo "Usage:"; \
			echo "  make check.NAME"; \
			echo "  make check.theme.NAME"; \
			echo "  make check.plugin.NAME"; \
			echo "  make check.mu-plugin.NAME"; \
			echo; \
			echo "Runs 'composer check' in the selected project."; \
			;; \
		test) \
			echo "Usage:"; \
			echo "  make test.NAME"; \
			echo "  make test.theme.NAME"; \
			echo "  make test.plugin.NAME"; \
			echo "  make test.mu-plugin.NAME"; \
			echo; \
			echo "Runs 'composer test' in the selected project."; \
			;; \
		check.npm) \
			echo "Usage:"; \
			echo "  make check.npm.NAME"; \
			echo "  make check.npm.theme.NAME"; \
			echo "  make check.npm.plugin.NAME"; \
			echo "  make check.npm.mu-plugin.NAME"; \
			echo; \
			echo "Runs 'npm run check' in the selected project."; \
			echo "If .nvmrc exists, its Node version must already be installed."; \
			;; \
		test.npm) \
			echo "Usage:"; \
			echo "  make test.npm.NAME"; \
			echo "  make test.npm.theme.NAME"; \
			echo "  make test.npm.plugin.NAME"; \
			echo "  make test.npm.mu-plugin.NAME"; \
			echo; \
			echo "Runs 'npm run test' in the selected project."; \
			echo "If .nvmrc exists, its Node version must already be installed."; \
			;; \
		node.install) \
			echo "Usage:"; \
			echo "  make node.install.VERSION"; \
			echo; \
			echo "Examples:"; \
			echo "  make node.install.20"; \
			echo "  make node.install.20.20.2"; \
			;; \
		node.list) \
			echo "Usage:"; \
			echo "  make node.list"; \
			echo; \
			echo "Lists Node versions installed through NVM."; \
			;; \
		wp) \
			echo "Usage:"; \
			echo "  make wp"; \
			echo; \
			echo "Runs WP-CLI inside the WordPress container."; \
			;; \
		*) \
			echo "No help available for: $*"; \
			echo "Run 'make help' to see available commands."; \
			exit 1; \
			;; \
	esac

info:
	@printf '\033[1;36mWP Lab\033[0m\n'
	@printf '\033[2m'; \
	i=0; while [ $$i -lt 60 ]; do printf '─'; i=$$((i + 1)); done; \
	printf '\033[0m\n'

	@printf '\033[1mSite\033[0m\n'
	@printf '  %-12s %s\n' 'Name' '$(SITE_NAME)'
	@printf '  %-12s \033[36m%s\033[0m\n' 'URL' '$(SITE_URL)'
	@printf '\n'

	@printf '\033[1mStack\033[0m\n'
	@printf '  %-12s %s\n' 'WordPress' '$(WP_VERSION)'
	@printf '  %-12s %s\n' 'PHP' '$(PHP_VERSION)'
	@printf '  %-12s %s\n' 'MariaDB' '$(MARIADB_VERSION)'
	@printf '\n'

	@printf '\033[1mLogin\033[0m\n'
	@printf '  %-12s %s\n' 'Username' '$(ADMIN_USER)'
	@printf '  %-12s \033[33m%s\033[0m\n' 'Password' '$(ADMIN_PASS)'
	@printf '\n'

	@printf '\033[1mMultisite\033[0m\n'
	@printf '  %-12s %s\n' 'Enabled' '$(MULTISITE_ENABLED)'
	@printf '  %-12s %s\n' 'Mode' '$(MULTISITE_MODE)'
	@printf '\n'

